# Configuración de JWT
app.jwt.secret=JWT123456789
app.jwt.expiration=86400000

# Configuración de MySQL dentro de Docker
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/gestorgranja}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:rancheroRoot}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:@admin123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA/Hibernate para la base de datos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Configuración del servidor
server.port=8081

# Configuración de logging
logging.level.org.springframework.security=INFO
logging.level.com.rancho.gestorGranja=INFO
logging.level.org.hibernate.SQL=INFO
