# Configuración de JWT
app.jwt.secret=JWT123456789
app.jwt.expiration=86400000


# Configuración de Azure MySQL
spring.datasource.url=jdbc:mysql://ranchobd.mysql.database.azure.com:3306/gestorgranja
# El usuario debe incluir el nombre del servidor
spring.datasource.username=rancheroRoot
spring.datasource.password=@admin123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Configuración JPA/Hibernate para la base de datos
spring.jpa.hibernate.ddl-auto=update
# Mostrar las consultas SQL que ejecuta (opcional para debug)
spring.jpa.show-sql=true
# Dialecto SQL para MySQL 8
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


# Configuración del servidor
server.port=8081

# Configuración de logging
logging.level.org.springframework.security=DEBUG
logging.level.com.rancho.gestorGranja=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Configuración de conexión
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5
